version: '2'
services:
  # Our landing page application
  landing:
    network_mode: bridge
    image: "c7d686365b54"
    command: "oxy --rsvp"
    depends_on:
      - "builder"
    volumes:
      - "$PWD/_site:/src/www"
    labels:
      - "traefik.backend=landing"
      - "traefik.frontend.rule=Host:staticpages.local"
      - "traefik.enable=true"

  # Our landing page builder
  builder:
    image: "jekyll/jekyll:3.5.0"
    command: "./build.sh"
    depends_on:
      - "reverse-proxy"
    environment:
      - "JEKYLL_ENV=production"
    volumes:
      - "$PWD:/srv/jekyll"

  reverse-proxy:
    network_mode: bridge
    image: "traefik:1.3.8"
    command: "--debug --defaultentrypoints=http --entrypoints=Name:http Address::80 --docker --docker.watch --docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"